### ISSUE TITLE
infinite loop

### ISSUE THREAD

**Issue by toooni** [ysugimoto/aws-lambda-image#10]
If you don't want to specify a different target bucket, this script ends up in an infinite loop. I found a solution where a DynamoDB was used to avoid this case. But I thought that maybe adding a meta information like "x-amz-meta-optimized" with value 1 or something might be a solution. The Script then skips files with this meta tag.

The downside of this:
- Script runs twice (Is also happening when using a DB)
- Images do have an additional Meta-Tag

What do you think about this?

**Comment by ysugimoto** [comment]
That seems to be good solution. But, I think these downside cases too.

> Script runs twice (Is also happening when using a DB)

If JPEG image, resize image twice, quality is down. (but it may be better than infinite loop...)

> Images do have an additional Meta-Tag

I think that has no problem. Or something would be likely to be a problem?

I using this package to avoid infinite loop, Put the directory prefix of Lambda's event source settings (e.g. lambda/*) , and put different directory (same bucket) on this package's setting.

The But may, if there is other good workaround...

thanks.

**Comment by toooni** [comment]
> If JPEG image, resize image twice, quality is down. (but it may be better than infinite loop...)
Ah no, I just meant the script runs twice. On the beginning of the script should be a check if the Meta-Tag is already set. If it is, the resizing and optimizing are skipped.
> I think that has no problem. Or something would be likely to be a problem?
I don't think so either, no.

> I using this package to avoid infinite loop, Put the directory prefix of Lambda's event source settings (e.g. lambda/*) , and put different directory (same bucket) on this package's setting.
Unfortunately we do have a web-application which uses 3rdparty libraries. These libraries are not likely to configure to write and read in two separate directories (or Buckets).

So I might try to create a PR for that. It shouldn't be hard to read and write the Meta-Tag.

**Comment by ysugimoto** [comment]
> Ah no, I just meant the script runs twice. On the beginning of the script should be a check if the Meta-Tag is already set. If it is, the resizing and optimizing are skipped.

Oh yes, I was mistaken. I agree with you.

> So I might try to create a PR for that. It shouldn't be hard to read and write the Meta-Tag.

I'm looking forward to your PR!

**Comment by ysugimoto** [comment]
Close with PR #11 thanks!
