### ISSUE TITLE
Claudia.js handles only one Bucket

### ISSUE THREAD

**Issue by ysugimoto** [ysugimoto/aws-lambda-image#100]
A `claudia.js` is able to install only one such handler per Bucket.
issue: https://github.com/claudiajs/claudia/issues/101

If this issue has solved, update documentation.

**Comment by kdybicz** [comment]
It has been solved in Claudia. We need to wait for build containing those improvements, and update our dependencies.

**Comment by kdybicz** [comment]
There is a Pull Request almost ready https://github.com/ysugimoto/aws-lambda-image/pull/108 that will solve this issue.

**Comment by kdybicz** [comment]
Fix merged into master. We can bump the version and push new release.
