### ISSUE TITLE
No Makefile

### ISSUE THREAD

**Issue by VigneshPT** [ysugimoto/aws-lambda-image#112]
Since you don't have a makefile now. If I don't want to use the aws-cli do I just zip and upload?

**Comment by kdybicz** [comment]
Hi @VigneshPT,

Have you consider using https://www.npmjs.com/package/npm-bundle ? Using:
```
npm install -g npm-bundle

# The current directory containing a package.json
npm-bundle
```
seems to build legit package.

**Comment by VigneshPT** [comment]
@kdybicz Thanks for that suggestion. However, npm-bundle zips everything to a tarball. I needed a zip file to be uploaded in AWS Lambda. 

I just did `npm prune --production` then `zip zipfilename.zip ./` and got the zip file.
