### ISSUE TITLE
Ability to configure a delete option which deletes the uploaded (source bucket) files after completion.

### ISSUE THREAD

**Issue by mhuebner** [ysugimoto/aws-lambda-image#133]
This would be a very handy option as you would have a feedback on which files are completed.
Currently the uploaded files stay in their place. A workaround is to set option

```
"backup": {
      "directory": "./done"
  },
```

But with this solution your uploaded content stays in its place of course. It's just an option to look into ".done" folder which files were successfully processed.

**Comment by mhuebner** [comment]
Could also be implemented as a "move" option like in camel: http://camel.apache.org/file2.html

> 	Expression (such as File Language) used to dynamically set the filename when moving it after processing. To move files into a .done subdirectory just enter .done.

**Comment by ysugimoto** [comment]
Thanks for suggestion. 

I think it is useful by adding a new option key like:

```
"backup": {
  "directory": "./done",
  "move": true
}
```

What do you think about this?

**Comment by mhuebner** [comment]
This would be exactly what I need. 
Thank you for looking into this issue!

**Comment by ysugimoto** [comment]
We've implemented this feature.

**Comment by mhuebner** [comment]
Great news. Thanks a lot!

**Comment by ysugimoto** [comment]
@mhuebner Yep, this implementation had already merged at master branch. Please check out latest and try it!
