### ISSUE TITLE
"Error: spawn EACCES" on image upload after deploying

### ISSUE THREAD

**Issue by stormcrow85** [ysugimoto/aws-lambda-image#143]
Hi,

After running into many issues I successfully deployed the function to Lambda. Uploading an image triggers the function. In CloudWatch logs I'm getting:

**Reducing to: ./reduced
{"errorMessage":"Error processing original/my-image.jpg: Error: spawn EACCES"}**

Did anyone encounter this? from what I read it's not an aws permission issue but an NPM issue.

Thanks!

**Comment by wandri** [comment]
I have the same issue.

"errorMessage": "Error processing photos/-KsDt7AupIzmQaYLxH74.jpg: Error: spawn EACCES"

My permission allows me a full access to S3.

**Comment by ysugimoto** [comment]
@stormcrow85 @wandri 

I guess `EACCESS` means permission related error. But this project deals with S3 files as binary string, so permission isn't cause of that.

However, image reduce binaries which bundled in this project might not have a permission when packaging. So could you try to add a executable permission?

```
$ chmod +x bin/linux/*
```

Or, try this branch: https://github.com/ysugimoto/aws-lambda-image/tree/feature-binary-permission This branch works apply executable permission before spawn process.

**Comment by stormcrow85** [comment]
Thanks @ysugimoto

I'm using the branch feature-binary-permission

I am now getting:

**"errorMessage": "Error processing myImage.jpg: Error: EROFS: read-only file system, chmod '/var/task/bin/linux/cjpeg'"**

I've read that some people were able to bypass this with writing the files to the /tmp folder, but i am getting the impression that this is not a good practice, and in 2017 it's not needed anymore on Lambda.

With that being said, I still cannot find any way to make this work

I also tried deploying the code on an EC2 instance with an identical environment to Lambda, and copying the files from there, also didn't work for me

**Comment by ysugimoto** [comment]
@stormcrow85 Thank you for reporting.

I investigated, and the [serverless](https://github.com/serverless/serverless) fixes as you said: https://github.com/serverless/serverless/pull/1631 

If this problem caused by zip file, probably we confirm how `Claudia.js` makes it.

> and in 2017 it's not needed anymore on Lambda.

Wow, where could I see that information?

**Comment by stormcrow85** [comment]
Thanks for investigating @ysugimoto, I'm looking into the fix you mentioned.

Regarding chmod and moving files to tmp folder (on Lambda) - see the following answer:
`https://stackoverflow.com/a/29001078/1185447`

**Comment by stormcrow85** [comment]
Hi @ysugimoto 

Finally, it's working. I reverted back to the original repo and started from scratch.

- I created a new EC2 instance with environment identical to Lambda:

AMI name: amzn-ami-hvm-2016.03.3.x86_64-gp2
Linux kernel version – 4.4.51-40.60.amzn1.x86_64
Node.js – v4.3.2 and 6.10.3

- Git clone to local folder and uploaded to EC2

-  `chmod +x bin/linux/*`

- `npm install . `

- zipped the folder on EC2 using bash zip, and uploaded to Lambda

- Image is processed successfully after triggering image upload from S3 bucket


Just writing this as a future reference for anyone who might encounter this:

I figured that probably using a Windows machine is at fault here. The only time I was able to get it to work is by deploying, chmod and zipping on the EC2 linux machine. I suspect that like the issue referenced above the Unix permissions are not saved correctly in the zip file.

Thanks for all the assistance @ysugimoto

**Comment by ysugimoto** [comment]
Sounds great!

Well, on windows, it might be better to work on virtual env (eg `Vagrant`, `docker`) to create zip archive and uploading via `Claudia.js`.

I'll add virtual machine setting file for windows and look into [node-archiver](https://github.com/archiverjs/node-archiver) which uses at `Claudia.js`.

Thank you for solving problem @stormcrow85
