### ISSUE TITLE
Can it keep jpeg extension?

### ISSUE THREAD

**Issue by jerrychen1013** [ysugimoto/aws-lambda-image#149]
After upload jpeg and trigger Lambda, it would transfer jpeg to jpg, how could it do to keep jpeg extension?

Thank you

This is my config
```
{
  "bucket": 
 "myBucket",
  "reduce": {
      "directory": "./reduce",
      "prefix": "/",
      "quality": 80,
      "acl": "public-read"
  }
}
```

**Comment by aaroncrawford** [comment]
Same issue with people uploading .JPG - the system then looks for the JPG, but this script exports everything to .jpg

**Comment by ysugimoto** [comment]
We'll add more configuration which keeps original extension, thanks.

**Comment by aaroncrawford** [comment]
@ysugimoto Thank you for all the hard work!

**Comment by ysugimoto** [comment]
@aaroncrawford @jerrychen1013 We added to keep original extension feature by https://github.com/ysugimoto/aws-lambda-image/pull/160. Please try it with `keepExtension` set `true`.
