### ISSUE TITLE
Node v10 support

### ISSUE THREAD

**Issue by comiewcom** [ysugimoto/aws-lambda-image#181]
Hello.
Do you have plans to support Node v10?
Thank you for the wonderful project.

**Comment by ysugimoto** [comment]
Hi, @comiewcom 

Yes, out code also works fine on nodejs v10.15 😄  see tests: https://travis-ci.org/ysugimoto/aws-lambda-image/jobs/552600640

But claudia.js doesn't support to create function as runtime nodejs v.10.15, it's 8.10 as default.

Fortunately, claudia.js accepts `--runtime` argument in CLI, so probably you can add `--runtime node10.15` (maybe option value is different), then claudia.js creates a function with nodev10.15 runtime. I'm happy if you try and tell me how option works correctly!

**Comment by mamaremere** [comment]
Node v10.x still does not seem to be supported. There are two more tickets mentioning this and I also can confirm that with Node 10.x I get the following error message:

```
2019-11-19T14:47:44.727Z	45258927-a072-4a8e-be0f-13a248be66bc	INFO	Parsing S3 event...
2019-11-19T14:47:44.748Z	45258927-a072-4a8e-be0f-13a248be66bc	INFO	Downloading: uploads/image.jpeg
2019-11-19T14:47:44.838Z	45258927-a072-4a8e-be0f-13a248be66bc	INFO	Resizing to: ../properties
2019-11-19T14:47:44.850Z	45258927-a072-4a8e-be0f-13a248be66bc	ERROR	Invoke Error	
{
    "errorType": "Error",
    "errorMessage": "Error processing uploads/image.jpeg: Error: Stream yields empty buffer",
    "stack": [
        "Error: Error processing uploads/image.jpeg: Error: Stream yields empty buffer",
        "    at _homogeneousError (/var/runtime/CallbackContext.js:13:12)",
        "    at postError (/var/runtime/CallbackContext.js:30:51)",
        "    at callback (/var/runtime/CallbackContext.js:42:7)",
        "    at /var/runtime/CallbackContext.js:105:16",
        "    at processor.run.then.catch (/var/task/index.js:55:13)",
        "    at process._tickCallback (internal/process/next_tick.js:68:7)"
    ]
}

END RequestId: 45258927-a072-4a8e-be0f-13a248be66bc
```

The two tickets mentioning issues with v10.x are: [#183](https://github.com/ysugimoto/aws-lambda-image/issues/183) and #186

**Comment by ysugimoto** [comment]
@mamaremere Could I get the image which you uploaded? I'll try to reproduce.

**Comment by mamaremere** [comment]
@ysugimoto, sure. I've attached it to this comment (fine art from my niece 😀).

![image](https://user-images.githubusercontent.com/494753/69231664-24473a80-0b92-11ea-9c9e-942c8f340dc4.jpeg)

**Comment by ysugimoto** [comment]
@mamaremere nice picture 😄 thanks!

I figured maybe it is `gm` package issue and wrote at https://github.com/ysugimoto/aws-lambda-image/issues/186#issuecomment-555943933

I didn't realize `gm` has a memory limit, so probably I can fix large image issues like https://github.com/ysugimoto/aws-lambda-image/issues/31 and try to fix the problem
