### ISSUE TITLE
Original Image's width less then resize width

### ISSUE THREAD

**Issue by kyjin** [ysugimoto/aws-lambda-image#37]
I don't guarantee original image's width large then resize width.
 - original image's width : 800 < resize image width : 1000
 - "errorMessage": "Woops, image process failed: ImageMagick errError: Command failed: "

So, I wanna copy original image to thumbnail bucket, when origin image's width less then resize image width.

How can I do?

**Comment by ysugimoto** [comment]
@kyjin For example , Do you want to solve and write a judgment condition to use the original problem with the settings?

**Comment by kyjin** [comment]
@ysugimoto Yes. I want to solve two case.
1. original image's width > resize image's width ->  make thumbnail(General Action)
2. original image's width < resize image's width -> just copy original image source to destination S3
