### ISSUE TITLE
Support crop functionality

### ISSUE THREAD

**Issue by SamiSammour** [ysugimoto/aws-lambda-image#38]
Hello there guys,
Great work you've done here but I want to ask if there is a crop functionality in the project or should I do it and make a pull request for it.

**Comment by joshuamcginnis** [comment]
There is no crop functionality. You'd have to think through how introducing crop would impact config because some users may want to crop only and others may want to crop and resize concurrently.

**Comment by chamini2** [comment]
Maybe implement it as a plugin, rather than part of the project itself and point to it in the README?

**Comment by joelpurra** [comment]
Am also looking to crop pictures to certain sizes, filling the given size/area similar to what CSS [`background-size: cover`](https://developer.mozilla.org/en-US/docs/Web/CSS/background-size) does.

@joshuamcginnis: have a look at #52 for my suggestion for an extensible config.

**Comment by zeroasterisk** [comment]
> zoom crop
>
> convert $input -resize '$widthx$height^' -gravity center -crop '$widthx$height+0+0' $output

http://stackoverflow.com/a/18763097/194105
