### ISSUE TITLE
Expires Headers removed

### ISSUE THREAD

**Issue by scottybo** [ysugimoto/aws-lambda-image#44]
When we upload files to S3 we set an expires header on the object to a year in the future.

Creating a new image from the uploaded image seems to strip this expires header. Is there any way to make it keep the original header information?

This page has some useful info:
http://www.bucketexplorer.com/documentation/amazon-s3--how-to-set-cache-control-header-for-s3-object.html

**Comment by arthurlataks** [comment]
I suppose this can be the right place to do so : https://github.com/ysugimoto/aws-lambda-image/blob/master/libs/S3.js#L39

**Comment by scottybo** [comment]
Brilliant, thank you!

Just in case someone else comes across this issue, I changed the line to:

            CacheControl: 'max-age = 31536000, must re-validate'
