### ISSUE TITLE
Support file type conversion

### ISSUE THREAD

**Issue by tlvince** [ysugimoto/aws-lambda-image#45]
Including an option to convert between file formats, e.g. to normalise `jpeg` and `png` to `jpg` would be useful in cases where there should be a canonical image, e.g. for user profile pictures.

**Comment by arthurlataks** [comment]
Maybe this will be useful for you: 

I am using `jonblum:jquery-cropper` ([link to jquery plugin](https://fengyuanchen.github.io/cropper/)) and when user crops image as he wants to I just force the canvas data to be jpeg 

```
var file = template.$('#preview').cropper('getCroppedCanvas', {
    width: Gallery.dimensions.regular.width,
    height: Gallery.dimensions.regular.height,
    fillColor: '#fff'
}).toDataURL('image/jpeg');
```

And technically there is no difference between jpeg and jpg, this is one format ([take a look at the top answer](http://stackoverflow.com/questions/23424399/jpg-vs-jpeg-image-formats))

And just in case, here is the config I found to be optimal for the cropping tool (I am forcing users to upload 550x550 images, so I styled my container for cropper to be square shape all the time, this gave me best results)
```
.cropper({
    aspectRatio: 1,
    dragMode: 'move',
    cropBoxMovable: false,
    responsive: true,
    cropBoxResizable: false,
    scalable: true,
    autoCropArea: 1,
    toggleDragModeOnDblclick: false,
    viewMode: 3,
    guides: false,
    center: false
});
```
