### ISSUE TITLE
Using aws-lambda-image with different regions

### ISSUE THREAD

**Issue by johnmore** [ysugimoto/aws-lambda-image#51]
Hello there I'm struggling to use this function since my bucket is on the eu-west-1 region (I'm from Portugal so...).

Tried to update configs for aws-sdk using `aws.config.update({region: 'eu-west-1'});` on the S3.js file just after your aws require but with had no luck whatsoever... lambda still gives me `{
  "errorMessage": "Woops, image process failed: S3 getObject failed: PermanentRedirect: The bucket you are attempting to access must be addressed using the specified endpoint. Please send all future requests to this endpoint."
}`

Any help you could get me is extremely appreciated!

Edit: I also tried getting a `region: "eu-west-1"` onto your `const client` var definition... again with no luck...

**Comment by pinpic** [comment]
Hi there,
I'm having the same problem but S3 and Lambda are on same region. Any ideas what I'm doing wrong? I do have error message:
`  "errorMessage": "Woops, image process failed: S3 getObject failed: PermanentRedirect: The bucket you are attempting to access must be addressed using the specified endpoint. Please send all future requests to this endpoint."`

Thanks,
Alen

**Comment by mordka** [comment]
I encountered the same issue which appeared to be test file problem. You need to update bucket name in few places (use as a ref: http://stackoverflow.com/questions/28022803/what-is-wrong-with-my-aws-lambda-function)
![image](https://cloud.githubusercontent.com/assets/3659502/17879858/623d877e-68f5-11e6-879e-6ee509ca3702.png)

**Comment by davidjeddy** [comment]
following
