### ISSUE TITLE
Utilising lambda outside of S3 Events

### ISSUE THREAD

**Issue by Dayjo** [ysugimoto/aws-lambda-image#54]
Hello again,

I've been thinking about my specific usage needs and am considering calling this function from SNS instead of via the S3 Event. 

Can you see any downside to doing this, or anything significant that I would need to change for this to work (other than it getting the S3 object details from the `event.Records`)?

If anyone has already successfully done this, it'd be cool to hear how.

**Comment by kdybicz** [comment]
Hi, I should be able to prepare a Pull Request covering this case in the next couple of days.

**Comment by kdybicz** [comment]
Feel free to test this branch https://github.com/ysugimoto/aws-lambda-image/tree/adding-sns-support I will prepare Pull Request for it as soon I will figure out how to test that new part properly.

**Comment by kdybicz** [comment]
Feature merged to master, will be release soon.

**Comment by Dayjo** [comment]
Lovely stuff! Great work @kdybicz :)
