### ISSUE TITLE
Ability to use defined ImageMagick geometry within config.json

### ISSUE THREAD

**Issue by brok3nstrings** [ysugimoto/aws-lambda-image#56]
I'm attempting to set a max width/height and retain aspect ratio.

> "size": "144x144",

With the size defined it only uses calculated width, with height exceeding the defined size parameter.

_Proposed config.json example;_

```
"size": "100x200"          # width = 100, height = 200, retains aspect ratio

"size": "300x"             # width = 300, height = proportional

"size": "x300"             # width = proportional, height = 300
```

**Comment by ysugimoto** [comment]
@brok3nstrings Please use `width` or `height` option value instead of `size`.
Sorry for this isn't written in README.

https://github.com/ysugimoto/aws-lambda-image/blob/master/libs/ImageResizer.js#L35

**Comment by brok3nstrings** [comment]
Without the size definition, the configtest outputs a fatal error warning:

`[Fatal] Resize destination size must be supplied ( at index 0 )`
