### ISSUE TITLE
Preserve Relative Path

### ISSUE THREAD

**Issue by aleemb** [ysugimoto/aws-lambda-image#59]
If an image is uploaded in `foo/bar/image.png` then it would be best if the resized images were added to `/resized/small/foo/bar/image.png` instead of the current behaviour of putting it in `resized/small/image.png`. This would allow apps that use custom paths to work better.

**Comment by Webpal** [comment]
Simple fix if you know all your images are in sub-folders, in ImageReducer.js, replace "dir + image.baseName" with "dir + image.dirName + "/" + image.baseName,"

**Comment by aleemb** [comment]
The PR is tested across root and sub-folders as well as with and without `options.directory`. If you could merge that would be swell 😄

**Comment by aleemb** [comment]
@Webpal thanks for the pointer. A minor nitpick `dir + image.dirName + "/" + image.baseName` will be buggy if image is uploaded to bucket root, resulting in two slashes.

**Comment by tusharvikky** [comment]
Hello @ysugimoto I was trying to replicate this in latest build. But couldn't get it to work.

Any help would be great.
