### ISSUE TITLE
gif images not working

### ISSUE THREAD

**Issue by elrob** [ysugimoto/aws-lambda-image#60]
We are using the current version 6bac5b501efd06090dca412af3d64030d4fcda0a

png and jpg images are working as expected.

We are using 4 different sizes.

However, gif images are being saved as 0 byte files at all 4 sizes.

Any ideas?

**Comment by elrob** [comment]
Just to confirm, I've cloned the repo fresh, used the sample config file along with the test fixture images.
The pngs and jpgs seem to work fine.
The reduced gif works fine. 
The resized comes out as 0 bytes.

**Comment by kdybicz** [comment]
@elrob I believe this should be already solved.

**Comment by kdybicz** [comment]
@elrob I will close the ticket, because I did test gif conversion and it was working fine. If the issue happens for you after updating to latest version, do not hesitate to re-open it and give bit more details, like configuration used or example files. Cheers!
