### ISSUE TITLE
Stream yields empty buffer

### ISSUE THREAD

**Issue by alexdrans** [ysugimoto/aws-lambda-image#61]
Hi,

I'm having trouble getting this to work. When I set it up on AWS, the function timed out, so I ran the tests locally and the final 5 tests are failing with the error ``Stream yields empty buffer``. I assume this is related to why the function times out on AWS, but I don't know why?

**Comment by davidascher** [comment]
I'm having the same issue, @alexdrans  -- how did you fix it (if you did)?

**Comment by alexdrans** [comment]
The error went away when I stopped uploading via the management console and used the CLI instead IIRC. The repo has a deploy script which isn't mentioned in the README.

**Comment by maiers** [comment]
Potentially the same here. I used the AWS js sdk to trigger the lambda. Out of about a hundred images, about 20 would not be resized at all. Most common error is `Stream yields empty buffer`, but I also got `ENOMEM` and `spawn E2BIG`.

The same with resized and quality reduced copies of one of the files. Any ideas?
