### ISSUE TITLE
Format Conversion Not Working

### ISSUE THREAD

**Issue by mark100net** [ysugimoto/aws-lambda-image#63]
I am using the version with the latest commit (adding the format conversion) so I as I understand it, using the below configuration, if I upload a .png I should get a .jpg in the resized/600-jpeg folder.

However what I am getting is a .png with the same name and with 0 bytes. I have tried various original sizes but always get this result. 

The other resizes (which do not contain the format key) are working properly.

Can anyone suggest what might be wrong?

{
  "reduce": {
      "directory": "reduced",
      "quality": 90
  },
  "resizes": [
    {
      "size": 300,
      "directory": "resized/small"
    },
    {
      "size": "600x600^",
      "gravity": "Center",
      "crop": "600x600",
      "directory": "resized/cropped-to-square"
    },
    {
      "size": 600,
      "directory": "resized/600-jpeg",
      "format": "jpg",
      "background": "white"
    },
    {
      "size": 900,
      "directory": "resized/large",
      "quality": 90
    }
  ]
}

**Comment by odedniv** [comment]
+1
I'm getting 0 byte file for the reduced version.

**Comment by dariospadoni** [comment]
+1

**Comment by seanzoucn** [comment]
+1

**Comment by kdybicz** [comment]
@mark100net can you please check again. We did improved a bit the format conversion flow.
