### ISSUE TITLE
Permissions

### ISSUE THREAD

**Issue by briank-musichouse** [ysugimoto/aws-lambda-image#64]
I find that after processing, my images are no longer publicly viewable. I solved this by adding the following before line 51 of libs/s3.js:
`ACL:          'public-read',`

It would be great to add a line for configuring upload permissions to config.json so that no modification of other files is necessary.

**Comment by emadb** [comment]
It seems that there is already a setting for this. In the same file [s3.js#L61](https://github.com/ysugimoto/aws-lambda-image/blob/master/libs/S3.jsl#L61) it read the acl from the image. So you could try to add the setting in the `config.json` file.

**Comment by ysugimoto** [comment]
I wrote about `acl` parameter at README. thanks.
