### ISSUE TITLE
Resize image when larger than specified size

### ISSUE THREAD

**Issue by dariospadoni** [ysugimoto/aws-lambda-image#72]
Hello
I'm trying to resize images only if their original width is larger than 1200px and to do that I'm using this option:

```
"resizes": [
    {
      "size": "1200x>",
      "directory": "./optimized/hero",
      "quality": 90,
      "format": "jpg"
    }
  ]
```

which (as far as I understood) should resize the image only if it's larger than 1200px. However I see that also images smaller are enlarged to fit that width. Is my configuration wrong?
One more question: what happens to images which do not match the size condition? Will they anyway be transferred in the destination folder and only compressed (90%)?

**Comment by kdybicz** [comment]
To figure out what size values you should use please refer to [ImageMagic - Image Geometry](http://imagemagick.org/script/command-line-processing.php#geometry) documentation. There is an option similar to the one you use: `widthxheight> - Shrinks an image with dimension(s) larger than the corresponding width and/or height argument(s).` but it includes both width and height.

As for the other part of the question, the answer is yes. Those images still would be transferred and optimised to meet 90% compression level.

**Comment by raza2022** [comment]
@dariospadoni have you implemented the required functionality ? because I want same functionality as if the Pic should be reduced if and only if the size is 1200x or greater.
@kdybicz if you give any suggestion will greatly appreciated by the way great thanks to all maintainers for a excellent module :+1:  @ysugimoto

**Comment by dariospadoni** [comment]
@raza2022 I implemented it, check [here](https://github.com/dariospadoni/aws-lambda-image-compressor)

**Comment by raza2022** [comment]
@dariospadoni Thanks :+1:
