### ISSUE TITLE
PNG images not working

### ISSUE THREAD

**Issue by dariospadoni** [ysugimoto/aws-lambda-image#73]
Hello
I can't make the function process uploaded PNG imges: it works for jpg but for png files I've got the following error when I run the test:

```
START RequestId: 8d7fd305-a8ff-11e6-b6bb-ed7d87bbb1aa Version: $LATEST
2016-11-12T17:43:50.679Z	8d7fd305-a8ff-11e6-b6bb-ed7d87bbb1aa	Error: write EPIPE
    at Object.exports._errnoException (util.js:870:11)
    at exports._exceptionWithHostPort (util.js:893:20)
    at WriteWrap.afterWrite (net.js:763:14)
END RequestId: 8d7fd305-a8ff-11e6-b6bb-ed7d87bbb1aa
REPORT RequestId: 8d7fd305-a8ff-11e6-b6bb-ed7d87bbb1aa	Duration: 8153.01 ms	Billed Duration: 8200 ms 	Memory Size: 256 MB	Max Memory Used: 137 MB	
Process exited before completing request
```

Here's my configuration

```{
  "bucket": "my-bucket",
  "reduce": {
      "directory": "./reduced",
      "quality": 90
  },
  "resizes": [
    {
      "size": 300,
      "directory": "./resized/small"
    },
    {
      "size": "600x600^",
      "gravity": "Center",
      "crop": "600x600",
      "directory": "./resized/cropped-to-square"
    },
    {
      "size": 600,
      "directory": "./resized/600-jpeg",
      "format": "jpg",
      "background": "white"
    },
    {
      "size": 900,
      "directory": "./resized/large",
      "quality": 90
    }
  ]
}

```

Any hint?

**Comment by accilies** [comment]
Same issue here...

**Comment by dariospadoni** [comment]
I ended up writing my own lambda function: https://github.com/dariospadoni/aws-lambda-image-compressor 
Hope it helps.

**Comment by Weijtmans** [comment]
Same here.

**Comment by ArturGrigio** [comment]
Similar issue here. if you have .JPG or .jpeg or .JPEG, the lambda won't run... Any suggestions?

**Comment by sbuys** [comment]
PNG works for me but is incredibly slow. My lambda function is timing out.

Might want to try increasing timeout duration or memory you've assigned to your lambda function.

I'm going to try switching to [sharp](https://github.com/lovell/sharp) (which uses libvips and benchmarks much faster than gm/imagemagick). [This guy](https://petar.io/post/fast-image-resizing-aws-lambda/) has a nice write-up of how to implement.

**Comment by claudeschneider** [comment]
This has been working fine for us, except for PNG images, which are INCREDIBLY slow to resize. For a 2Mp PNG image (only about 300kb), it can take over 30 seconds to resize.

I'd like to use 'sharp', sadly there are no ready-made code examples for S3-lambda resizing, allowing a direct swap-out with this library.

I'm going to try using Sharp instead of the provided Optimizers - if anyone has tried this, please do share any learnings/code!

**Comment by kdybicz** [comment]
We have pushed some new binaries, compiled for Lambda environment. It's not release yet, but you should be able to run some tests on our `master` branch.
