### ISSUE TITLE
"OK, 1 images were processed." but not saving images

### ISSUE THREAD

**Issue by marioperezpereira** [ysugimoto/aws-lambda-image#74]
Configured the function with proper permissions and trigger (Event type: ObjectCreated). On cloudwatch it reflects that images are processed perfectly but inside the bucket there is no trace of the processed files.

**Comment by sfisico** [comment]
It might have timed out. Try increasing the time out of your lambda function.

**Comment by kdybicz** [comment]
@marioperezpereira did increasing the Timeout value helped?
