### ISSUE TITLE
Assertions in tests are not working

### ISSUE THREAD

**Issue by kdybicz** [ysugimoto/aws-lambda-image#86]
There is a problem while using `t.is(...)` and other `t.`'s in callback methods, in this case inside     `gm(destPath).size((err, out) => { ... });`. There is a word or two about something similar in the [AVA - common-pitfalls](https://github.com/avajs/ava/blob/master/docs/common-pitfalls.md#asynchronous-operations) documentation, but I was unable to force `pify()` to work together with `gm`.

Here you have an example of a test that should fail, but it's passing:
```
test("Resize JPEG with cjpeg", async t => {
    const fixture = await fsP.readFile(`${__dirname}/fixture/fixture.jpg`);
    const destPath = `${__dirname}/fixture/fixture_resized_1.jpg`;
    const resizer = new ImageResizer({size: 200});
    const image   = new ImageData("fixture/fixture.jpg", "fixture", fixture);

    const resized = await resizer.exec(image);
    await fsP.writeFile(destPath, resized.data);
    gm(destPath).size((err, out) => {
        if ( err ) {
            t.fail(err);
        } else {
            t.is(out.width, 12345); // invalid image width
        }
        fs.unlinkSync(destPath);
    });
});
```

You can replace [this line](https://github.com/ysugimoto/aws-lambda-image/blob/master/test/resize-jpeg.js#L23) with `t.is(out.width, 12345);` to verify this in local env.

**Comment by kdybicz** [comment]
Fix proposal in https://github.com/ysugimoto/aws-lambda-image/pull/87

**Comment by ysugimoto** [comment]
Fixed in https://github.com/ysugimoto/aws-lambda-image/pull/91
