### ISSUE TITLE
windows compatibility

### ISSUE THREAD

**Issue by mattmeye** [ysugimoto/aws-lambda-image#95]
pls remove "make" and use package.json / node.js-scripts, i think you can bundle zip-file with node really easy

**Comment by kdybicz** [comment]
You can take a look at this PR https://github.com/ysugimoto/aws-lambda-image/pull/99/files and let us know how it's working for you.

**Comment by kdybicz** [comment]
Please check latest version. It's utilitizing `package.js` together with [Claudia.js](https://github.com/claudiajs/claudia) Hope it will work fine on Windows.
